#! /bin/sh
#pgrep bspswallow || bspswallow &
#nm-applet & 
feh --bg-fill /home/alu/Downloads/"dracula-waves-44475a.png" &
dunst &
xss-lock --transfer-sleep-lock -- betterlockscreen -l blur 1.0 &
picom &
#polybar --config=/home/alu/.config/polybar/draculabar example &
~/.killpulse.sh &
setxkbmap -option caps:escape &
xinput --set-prop "AlpsPS/2 ALPS DualPoint TouchPad" "libinput Accel Speed" 0.5 &
xinput --set-prop "AlpsPS/2 ALPS DualPoint TouchPad" "libinput Disable While Typing Enabled" 0 &
pgrep -x sxhkd > /dev/null || sxhkd &
xset s 300 300 &
xset dpms 300 300 300 &

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV

#bspc config ignore_ewmh_fullscreen all
bspc config border_width         2
bspc config window_gap          0
bspc config top_padding         0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
#bspc config border_radius 15
bspc config focus_follows_pointer true
#bspc config focused_border_color \#7de8a0
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#8be9fd" cyan
bspc config focused_border_color "#bb91f7"
bspc config presel_feedback_color "#6272a4"

